# Dockerfile para el backend
FROM python:3.10.0
# Usa la versión de Python adecuada para el backend

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de dependencias e instálalas
# Instalar dependencias en Dockerfile
COPY ./requirements.txt ./
RUN pip install -r requirements.txt


# Copia el código del backend en el contenedor
COPY ./ ./

# Recopila los archivos estáticos (para producción)
RUN python manage.py collectstatic

# Comando para iniciar el backend con Gunicorn
CMD ["sh", "entrypoint.sh"]