# Dockerfile para el chatbot
FROM python:3.10
# Usa la versión de Python adecuada para Rasa

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de dependencias e instálalas
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código del chatbot en el contenedor
COPY . .

# Entrena el modelo de Rasa
RUN rasa train

# Expone los puertos que utilizarán Rasa y las acciones
EXPOSE 5005 5055

# Usa supervisord para gestionar múltiples procesos (rasa run y rasa actions)
RUN pip install supervisor

# Copia el archivo de configuración de supervisord
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Comando para iniciar supervisord, que se encargará de correr los servicios de Rasa
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]